/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDemoApplePassRouteImport } from './routes/api/demo/apple-pass'
import { Route as ApiDemoGooglePassRouteImport } from './routes/api/demo/google-pass'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoApplePassRoute = ApiDemoApplePassRouteImport.update({
  id: '/api/demo/apple-pass',
  path: '/api/demo/apple-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoGooglePassRoute = ApiDemoGooglePassRouteImport.update({
  id: '/api/demo/google-pass',
  path: '/api/demo/google-pass',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/demo/apple-pass': typeof ApiDemoApplePassRoute
  '/api/demo/google-pass': typeof ApiDemoGooglePassRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/demo/apple-pass': typeof ApiDemoApplePassRoute
  '/api/demo/google-pass': typeof ApiDemoGooglePassRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/demo/apple-pass': typeof ApiDemoApplePassRoute
  '/api/demo/google-pass': typeof ApiDemoGooglePassRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/demo/apple-pass' | '/api/demo/google-pass'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/demo/apple-pass' | '/api/demo/google-pass'
  id: '__root__' | '/' | '/api/demo/apple-pass' | '/api/demo/google-pass'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDemoApplePassRoute: typeof ApiDemoApplePassRoute
  ApiDemoGooglePassRoute: typeof ApiDemoGooglePassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/apple-pass': {
      id: '/api/demo/apple-pass'
      path: '/api/demo/apple-pass'
      fullPath: '/api/demo/apple-pass'
      preLoaderRoute: typeof ApiDemoApplePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo/google-pass': {
      id: '/api/demo/google-pass'
      path: '/api/demo/google-pass'
      fullPath: '/api/demo/google-pass'
      preLoaderRoute: typeof ApiDemoGooglePassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDemoApplePassRoute: ApiDemoApplePassRoute,
  ApiDemoGooglePassRoute: ApiDemoGooglePassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
