/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedResetPasswordRouteImport } from './routes/_authed/reset-password'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as JoinProgramIdRouteImport } from './routes/join/$programId'
import { Route as AuthedProgramsProgramIdRouteImport } from './routes/_authed/programs/$programId'
import { Route as AuthedProgramsNewRouteImport } from './routes/_authed/programs/new'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as AuthedProgramsProgramIdIndexRouteImport } from './routes/_authed/programs/$programId/index'
import { Route as AuthedProgramsProgramIdNotificationsRouteImport } from './routes/_authed/programs/$programId/notifications'
import { Route as AuthedProgramsProgramIdScanRouteImport } from './routes/_authed/programs/$programId/scan'
import { Route as AuthedProgramsProgramIdSettingsRouteImport } from './routes/_authed/programs/$programId/settings'
import { Route as AuthedProgramsProgramIdShareRouteImport } from './routes/_authed/programs/$programId/share'
import { Route as ApiApplePassesSerialNumberRouteImport } from './routes/api/apple/passes/$serialNumber'
import { Route as ApiAppleV1LogRouteImport } from './routes/api/apple/v1/log'
import { Route as ApiGooglePassesSerialNumberRouteImport } from './routes/api/google/passes/$serialNumber'
import { Route as AuthedProgramsProgramIdMembersMemberIdRouteImport } from './routes/_authed/programs/$programId/members/$memberId'
import { Route as AuthedProgramsProgramIdMembersNewRouteImport } from './routes/_authed/programs/$programId/members/new'
import { Route as ApiAppleV1PassesPassTypeIdentifierSerialNumberRouteImport } from './routes/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
import { Route as ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRouteImport } from './routes/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/index'
import { Route as ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRouteImport } from './routes/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResetPasswordRoute = AuthedResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinProgramIdRoute = JoinProgramIdRouteImport.update({
  id: '/join/$programId',
  path: '/join/$programId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProgramsProgramIdRoute = AuthedProgramsProgramIdRouteImport.update({
  id: '/programs/$programId',
  path: '/programs/$programId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProgramsNewRoute = AuthedProgramsNewRouteImport.update({
  id: '/programs/new',
  path: '/programs/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProgramsProgramIdIndexRoute =
  AuthedProgramsProgramIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const AuthedProgramsProgramIdNotificationsRoute =
  AuthedProgramsProgramIdNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const AuthedProgramsProgramIdScanRoute =
  AuthedProgramsProgramIdScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const AuthedProgramsProgramIdSettingsRoute =
  AuthedProgramsProgramIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const AuthedProgramsProgramIdShareRoute =
  AuthedProgramsProgramIdShareRouteImport.update({
    id: '/share',
    path: '/share',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const ApiApplePassesSerialNumberRoute =
  ApiApplePassesSerialNumberRouteImport.update({
    id: '/api/apple/passes/$serialNumber',
    path: '/api/apple/passes/$serialNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAppleV1LogRoute = ApiAppleV1LogRouteImport.update({
  id: '/api/apple/v1/log',
  path: '/api/apple/v1/log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGooglePassesSerialNumberRoute =
  ApiGooglePassesSerialNumberRouteImport.update({
    id: '/api/google/passes/$serialNumber',
    path: '/api/google/passes/$serialNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedProgramsProgramIdMembersMemberIdRoute =
  AuthedProgramsProgramIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const AuthedProgramsProgramIdMembersNewRoute =
  AuthedProgramsProgramIdMembersNewRouteImport.update({
    id: '/members/new',
    path: '/members/new',
    getParentRoute: () => AuthedProgramsProgramIdRoute,
  } as any)
const ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute =
  ApiAppleV1PassesPassTypeIdentifierSerialNumberRouteImport.update({
    id: '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber',
    path: '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute =
  ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRouteImport.update(
    {
      id: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/',
      path: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute =
  ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRouteImport.update(
    {
      id: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber',
      path: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber',
      getParentRoute: () => rootRouteImport,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/reset-password': typeof AuthedResetPasswordRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/join/$programId': typeof JoinProgramIdRoute
  '/programs/$programId': typeof AuthedProgramsProgramIdRouteWithChildren
  '/programs/new': typeof AuthedProgramsNewRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/programs/$programId/notifications': typeof AuthedProgramsProgramIdNotificationsRoute
  '/programs/$programId/scan': typeof AuthedProgramsProgramIdScanRoute
  '/programs/$programId/settings': typeof AuthedProgramsProgramIdSettingsRoute
  '/programs/$programId/share': typeof AuthedProgramsProgramIdShareRoute
  '/api/apple/passes/$serialNumber': typeof ApiApplePassesSerialNumberRoute
  '/api/apple/v1/log': typeof ApiAppleV1LogRoute
  '/api/google/passes/$serialNumber': typeof ApiGooglePassesSerialNumberRoute
  '/programs/$programId/': typeof AuthedProgramsProgramIdIndexRoute
  '/programs/$programId/members/$memberId': typeof AuthedProgramsProgramIdMembersMemberIdRoute
  '/programs/$programId/members/new': typeof AuthedProgramsProgramIdMembersNewRoute
  '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber': typeof ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute
  '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber': typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute
  '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/': typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/reset-password': typeof AuthedResetPasswordRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/join/$programId': typeof JoinProgramIdRoute
  '/programs/new': typeof AuthedProgramsNewRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/programs/$programId/notifications': typeof AuthedProgramsProgramIdNotificationsRoute
  '/programs/$programId/scan': typeof AuthedProgramsProgramIdScanRoute
  '/programs/$programId/settings': typeof AuthedProgramsProgramIdSettingsRoute
  '/programs/$programId/share': typeof AuthedProgramsProgramIdShareRoute
  '/api/apple/passes/$serialNumber': typeof ApiApplePassesSerialNumberRoute
  '/api/apple/v1/log': typeof ApiAppleV1LogRoute
  '/api/google/passes/$serialNumber': typeof ApiGooglePassesSerialNumberRoute
  '/programs/$programId': typeof AuthedProgramsProgramIdIndexRoute
  '/programs/$programId/members/$memberId': typeof AuthedProgramsProgramIdMembersMemberIdRoute
  '/programs/$programId/members/new': typeof AuthedProgramsProgramIdMembersNewRoute
  '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber': typeof ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute
  '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber': typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute
  '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier': typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/reset-password': typeof AuthedResetPasswordRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/join/$programId': typeof JoinProgramIdRoute
  '/_authed/programs/$programId': typeof AuthedProgramsProgramIdRouteWithChildren
  '/_authed/programs/new': typeof AuthedProgramsNewRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/_authed/programs/$programId/notifications': typeof AuthedProgramsProgramIdNotificationsRoute
  '/_authed/programs/$programId/scan': typeof AuthedProgramsProgramIdScanRoute
  '/_authed/programs/$programId/settings': typeof AuthedProgramsProgramIdSettingsRoute
  '/_authed/programs/$programId/share': typeof AuthedProgramsProgramIdShareRoute
  '/api/apple/passes/$serialNumber': typeof ApiApplePassesSerialNumberRoute
  '/api/apple/v1/log': typeof ApiAppleV1LogRoute
  '/api/google/passes/$serialNumber': typeof ApiGooglePassesSerialNumberRoute
  '/_authed/programs/$programId/': typeof AuthedProgramsProgramIdIndexRoute
  '/_authed/programs/$programId/members/$memberId': typeof AuthedProgramsProgramIdMembersMemberIdRoute
  '/_authed/programs/$programId/members/new': typeof AuthedProgramsProgramIdMembersNewRoute
  '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber': typeof ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute
  '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber': typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute
  '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/': typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/auth/confirm'
    | '/join/$programId'
    | '/programs/$programId'
    | '/programs/new'
    | '/api/google/callback'
    | '/programs/$programId/notifications'
    | '/programs/$programId/scan'
    | '/programs/$programId/settings'
    | '/programs/$programId/share'
    | '/api/apple/passes/$serialNumber'
    | '/api/apple/v1/log'
    | '/api/google/passes/$serialNumber'
    | '/programs/$programId/'
    | '/programs/$programId/members/$memberId'
    | '/programs/$programId/members/new'
    | '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
    | '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'
    | '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/reset-password'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/auth/confirm'
    | '/join/$programId'
    | '/programs/new'
    | '/api/google/callback'
    | '/programs/$programId/notifications'
    | '/programs/$programId/scan'
    | '/programs/$programId/settings'
    | '/programs/$programId/share'
    | '/api/apple/passes/$serialNumber'
    | '/api/apple/v1/log'
    | '/api/google/passes/$serialNumber'
    | '/programs/$programId'
    | '/programs/$programId/members/$memberId'
    | '/programs/$programId/members/new'
    | '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
    | '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'
    | '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_guest'
    | '/_authed/dashboard'
    | '/_authed/reset-password'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/signup'
    | '/auth/confirm'
    | '/join/$programId'
    | '/_authed/programs/$programId'
    | '/_authed/programs/new'
    | '/api/google/callback'
    | '/_authed/programs/$programId/notifications'
    | '/_authed/programs/$programId/scan'
    | '/_authed/programs/$programId/settings'
    | '/_authed/programs/$programId/share'
    | '/api/apple/passes/$serialNumber'
    | '/api/apple/v1/log'
    | '/api/google/passes/$serialNumber'
    | '/_authed/programs/$programId/'
    | '/_authed/programs/$programId/members/$memberId'
    | '/_authed/programs/$programId/members/new'
    | '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
    | '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'
    | '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  AuthConfirmRoute: typeof AuthConfirmRoute
  JoinProgramIdRoute: typeof JoinProgramIdRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiApplePassesSerialNumberRoute: typeof ApiApplePassesSerialNumberRoute
  ApiAppleV1LogRoute: typeof ApiAppleV1LogRoute
  ApiGooglePassesSerialNumberRoute: typeof ApiGooglePassesSerialNumberRoute
  ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute: typeof ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute
  ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute: typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute
  ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute: typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reset-password': {
      id: '/_authed/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthedResetPasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$programId': {
      id: '/join/$programId'
      path: '/join/$programId'
      fullPath: '/join/$programId'
      preLoaderRoute: typeof JoinProgramIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/programs/$programId': {
      id: '/_authed/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/programs/$programId'
      preLoaderRoute: typeof AuthedProgramsProgramIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/programs/new': {
      id: '/_authed/programs/new'
      path: '/programs/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof AuthedProgramsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/programs/$programId/': {
      id: '/_authed/programs/$programId/'
      path: '/'
      fullPath: '/programs/$programId/'
      preLoaderRoute: typeof AuthedProgramsProgramIdIndexRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/_authed/programs/$programId/notifications': {
      id: '/_authed/programs/$programId/notifications'
      path: '/notifications'
      fullPath: '/programs/$programId/notifications'
      preLoaderRoute: typeof AuthedProgramsProgramIdNotificationsRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/_authed/programs/$programId/scan': {
      id: '/_authed/programs/$programId/scan'
      path: '/scan'
      fullPath: '/programs/$programId/scan'
      preLoaderRoute: typeof AuthedProgramsProgramIdScanRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/_authed/programs/$programId/settings': {
      id: '/_authed/programs/$programId/settings'
      path: '/settings'
      fullPath: '/programs/$programId/settings'
      preLoaderRoute: typeof AuthedProgramsProgramIdSettingsRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/_authed/programs/$programId/share': {
      id: '/_authed/programs/$programId/share'
      path: '/share'
      fullPath: '/programs/$programId/share'
      preLoaderRoute: typeof AuthedProgramsProgramIdShareRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/api/apple/passes/$serialNumber': {
      id: '/api/apple/passes/$serialNumber'
      path: '/api/apple/passes/$serialNumber'
      fullPath: '/api/apple/passes/$serialNumber'
      preLoaderRoute: typeof ApiApplePassesSerialNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apple/v1/log': {
      id: '/api/apple/v1/log'
      path: '/api/apple/v1/log'
      fullPath: '/api/apple/v1/log'
      preLoaderRoute: typeof ApiAppleV1LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/passes/$serialNumber': {
      id: '/api/google/passes/$serialNumber'
      path: '/api/google/passes/$serialNumber'
      fullPath: '/api/google/passes/$serialNumber'
      preLoaderRoute: typeof ApiGooglePassesSerialNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/programs/$programId/members/$memberId': {
      id: '/_authed/programs/$programId/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/programs/$programId/members/$memberId'
      preLoaderRoute: typeof AuthedProgramsProgramIdMembersMemberIdRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/_authed/programs/$programId/members/new': {
      id: '/_authed/programs/$programId/members/new'
      path: '/members/new'
      fullPath: '/programs/$programId/members/new'
      preLoaderRoute: typeof AuthedProgramsProgramIdMembersNewRouteImport
      parentRoute: typeof AuthedProgramsProgramIdRoute
    }
    '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber': {
      id: '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
      path: '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
      fullPath: '/api/apple/v1/passes/$passTypeIdentifier/$serialNumber'
      preLoaderRoute: typeof ApiAppleV1PassesPassTypeIdentifierSerialNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/': {
      id: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/'
      path: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier'
      fullPath: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/'
      preLoaderRoute: typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber': {
      id: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'
      path: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'
      fullPath: '/api/apple/v1/devices/$deviceLibraryIdentifier/registrations/$passTypeIdentifier/$serialNumber'
      preLoaderRoute: typeof ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedProgramsProgramIdRouteChildren {
  AuthedProgramsProgramIdNotificationsRoute: typeof AuthedProgramsProgramIdNotificationsRoute
  AuthedProgramsProgramIdScanRoute: typeof AuthedProgramsProgramIdScanRoute
  AuthedProgramsProgramIdSettingsRoute: typeof AuthedProgramsProgramIdSettingsRoute
  AuthedProgramsProgramIdShareRoute: typeof AuthedProgramsProgramIdShareRoute
  AuthedProgramsProgramIdIndexRoute: typeof AuthedProgramsProgramIdIndexRoute
  AuthedProgramsProgramIdMembersMemberIdRoute: typeof AuthedProgramsProgramIdMembersMemberIdRoute
  AuthedProgramsProgramIdMembersNewRoute: typeof AuthedProgramsProgramIdMembersNewRoute
}

const AuthedProgramsProgramIdRouteChildren: AuthedProgramsProgramIdRouteChildren =
  {
    AuthedProgramsProgramIdNotificationsRoute:
      AuthedProgramsProgramIdNotificationsRoute,
    AuthedProgramsProgramIdScanRoute: AuthedProgramsProgramIdScanRoute,
    AuthedProgramsProgramIdSettingsRoute: AuthedProgramsProgramIdSettingsRoute,
    AuthedProgramsProgramIdShareRoute: AuthedProgramsProgramIdShareRoute,
    AuthedProgramsProgramIdIndexRoute: AuthedProgramsProgramIdIndexRoute,
    AuthedProgramsProgramIdMembersMemberIdRoute:
      AuthedProgramsProgramIdMembersMemberIdRoute,
    AuthedProgramsProgramIdMembersNewRoute:
      AuthedProgramsProgramIdMembersNewRoute,
  }

const AuthedProgramsProgramIdRouteWithChildren =
  AuthedProgramsProgramIdRoute._addFileChildren(
    AuthedProgramsProgramIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedResetPasswordRoute: typeof AuthedResetPasswordRoute
  AuthedProgramsProgramIdRoute: typeof AuthedProgramsProgramIdRouteWithChildren
  AuthedProgramsNewRoute: typeof AuthedProgramsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedResetPasswordRoute: AuthedResetPasswordRoute,
  AuthedProgramsProgramIdRoute: AuthedProgramsProgramIdRouteWithChildren,
  AuthedProgramsNewRoute: AuthedProgramsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  AuthConfirmRoute: AuthConfirmRoute,
  JoinProgramIdRoute: JoinProgramIdRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiApplePassesSerialNumberRoute: ApiApplePassesSerialNumberRoute,
  ApiAppleV1LogRoute: ApiAppleV1LogRoute,
  ApiGooglePassesSerialNumberRoute: ApiGooglePassesSerialNumberRoute,
  ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute:
    ApiAppleV1PassesPassTypeIdentifierSerialNumberRoute,
  ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute:
    ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierSerialNumberRoute,
  ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute:
    ApiAppleV1DevicesDeviceLibraryIdentifierRegistrationsPassTypeIdentifierIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
